spring:  ##@author woshizhuyijie @date 2024-12-22
  datasource:
    ## 数据库连接信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus
    username: root
    password: 123456
## 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    #password: yourPassword  # 如果没有密码，可以省略
    database: 0  # 默认数据库
    timeout: 2000  # 连接超时时间，单位：毫秒
    time-to-live: 600000  # 设置缓存过期时间（以毫秒为单位）
  cache:
      type=redis:

  ##mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
## 开启日志事物管理
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManage: debug
server:
  port: 8080